[project]
name = "evaluator_kupid"
version = "0.0.1"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
kupid_evaluator = "evaluator:main"